language: node_js
node_js:
  - "stable"
cache:
  directories:
    - "node_modules"

install:
  - npm install

services:
  - postgresql

before_script:
  - psql -c 'create database wetravel_test;' -U postgres

script:
  - npm test
 
after_success:
  - npm run coverage

env:
  -NODE_ENV=test


